language: python
python: "3.7"
sudo: required
dist: xenial
install:
  - pip install -r requirements.txt -r test-requirements.txt
script:
  - pytest -vv
  - find . -name '*.py' | xargs pylint
services:
  - postgresql
