# Generated by Django 2.2.3 on 2019-08-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
        ('blog', '0009_auto_20190813_1242'),
    ]

    operations = [
    ]
